package com.veggofresh.platform.common;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.SoftDelete;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.time.Instant;
import java.util.UUID;

/**
 * Abstract base entity providing common audit and lifecycle fields for all domain entities.
 *
 * <p>All module entities MUST extend this class. It provides:
 * <ul>
 *   <li>{@code id} — UUID primary key, generated by the database (BINARY(16) for efficient MySQL indexing)</li>
 *   <li>{@code createdAt} — set once at insert time, never updated</li>
 *   <li>{@code updatedAt} — updated on every merge/update</li>
 *   <li>{@code deletedAt} — soft-delete timestamp; {@code null} means the record is active</li>
 *   <li>{@code version} — optimistic locking counter; prevents lost-update race conditions</li>
 * </ul>
 *
 * <p>Soft delete: set {@code deletedAt = Instant.now()} and call save(). Do NOT call repository.delete().
 * Each repository should filter by {@code deletedAt IS NULL} by default using {@code @Where} on entities
 * or Spring Data Specifications.
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity {

    /**
     * Primary key — UUID stored as BINARY(16) for optimal MySQL B-tree index performance.
     * Generated by Hibernate using a UUID v4 strategy (random).
     */
    @Id
    @UuidGenerator(style = UuidGenerator.Style.RANDOM)
    @Column(columnDefinition = "BINARY(16)", updatable = false, nullable = false)
    private UUID id;

    /**
     * Timestamp of entity creation. Populated automatically by Hibernate on first insert.
     * Never updated after that.
     */
    @CreationTimestamp
    @Column(updatable = false, nullable = false)
    private Instant createdAt;

    /**
     * Timestamp of last update. Automatically refreshed by Hibernate on every merge.
     */
    @UpdateTimestamp
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * Soft-delete timestamp. {@code null} = record is active.
     * Set to {@code Instant.now()} to logically delete the record.
     * Hard deletes should be reserved for GDPR erasure flows only.
     */
    @Column
    private Instant deletedAt;

    /**
     * Optimistic locking version counter managed by JPA.
     * Prevents concurrent update conflicts (lost updates) at the database level.
     * Do not set this manually.
     */
    @Version
    @Column(nullable = false)
    private Long version;

    /**
     * Convenience method to check whether this entity has been soft-deleted.
     *
     * @return {@code true} if {@code deletedAt} is not null
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Soft-deletes this entity by setting {@code deletedAt} to the current instant.
     * The caller is responsible for persisting this change via the repository.
     */
    public void softDelete() {
        this.deletedAt = Instant.now();
    }
}
